# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Daub | Front-End Web Developer | Seattle, WA
email: brian.daub@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
    Brian Daub is a Front End Web Developer located in the Seatlle, WA area. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.briandaub.com"   # with the https protocol
enforce_ssl: "www.briandaub.com"  # the base hostname & protocol for your site
twitter_username: briandaub
github_username:  briandaub

# Build settings
markdown: kramdown

         